const imageFiles=['living-room.svg','master-bedroom.svg','detail-study.svg'];
const $=(s)=>document.querySelector(s); const $$=(s)=>document.querySelectorAll(s);
async function json(p){const r=await fetch(p);return r.json()}
function text(sel,key,obj){$$(sel).forEach(e=>{if(obj[key]!=null)e.textContent=obj[key]})}
(async()=>{let site=await json('content/site.json'),project=await json('content/project.json');try{site={...site,...JSON.parse(localStorage.getItem('nk-site')||'{}')};project={...project,...JSON.parse(localStorage.getItem('nk-project')||'{}')}}catch{};
$$('[data-site]').forEach(e=>e.textContent=site[e.dataset.site]||'');$$('[data-project]').forEach(e=>e.textContent=project[e.dataset.project]||'');
const em=$('[data-email]');em.textContent=site.email;em.href='mailto:'+site.email;const ph=$('[data-phone]');ph.textContent=site.phone;ph.href='tel:'+site.phone.replace(/\s/g,'');$('[data-linkedin]').href=site.linkedin;
$('#scope').innerHTML=(project.scope||[]).map(x=>`<li>${x}</li>`).join('');$('#materials').innerHTML=(project.materials||[]).map(x=>`<li>${x}</li>`).join('');
$('#gallery').innerHTML=(project.gallery||[]).map((g,i)=>`<figure><img src="assets/${imageFiles[i]||imageFiles[0]}" alt="${g.label} placeholder"><figcaption>${g.label}</figcaption></figure>`).join('');const modelScript=document.createElement('script');modelScript.type='module';modelScript.src='https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js';document.head.append(modelScript);const model=document.createElement('model-viewer');model.src='assets/final-model.glb';model.setAttribute('camera-controls','');model.setAttribute('auto-rotate','');model.setAttribute('shadow-intensity','1');model.setAttribute('alt','Interactive 3D model of the 2 BHK residential home');model.style.cssText='display:block;width:100%;height:520px;margin:55px 0;background:#e9e4dc';const modelTitle=document.createElement('p');modelTitle.className='index';modelTitle.textContent='INTERACTIVE 3D MODEL · COLLEGE PROJECT';$('#gallery').before(modelTitle,model);$('#year').textContent=new Date().getFullYear();
$('.menu').onclick=()=>{const n=$('nav');n.style.display=n.style.display==='flex'?'none':'flex'};})();
