const progress = document.querySelector('#progress');
const portrait = document.querySelector('.portrait-frame img');
if (portrait) portrait.src = 'assets/nandini-portrait.jpg';
const reveals = document.querySelectorAll('.reveal');
const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) entry.target.classList.add('visible'); }), { threshold: .12 });
reveals.forEach((item) => observer.observe(item));
window.addEventListener('scroll', () => { const max = document.documentElement.scrollHeight - innerHeight; progress.style.width = `${(scrollY / max) * 100}%`; });
document.querySelector('.menu-button').addEventListener('click', () => document.querySelector('.nav').classList.toggle('open'));
document.querySelectorAll('.nav a').forEach((link) => link.addEventListener('click', () => document.querySelector('.nav').classList.remove('open')));
if (location.hash === '#dashboard') document.querySelector('#dashboard').classList.add('open');
document.querySelector('.close-dashboard').addEventListener('click', () => { document.querySelector('#dashboard').classList.remove('open'); history.replaceState(null, '', '#top'); });
document.addEventListener('keydown', (event) => { if (event.key === 'Escape') document.querySelector('#dashboard').classList.remove('open'); });
